### ISSUE TITLE
The information of TCS

### ISSUE THREAD

**Issue by jaebaek** [jethrogb/sgx-utils#2]
Hi, I read the WINTEL-SGX-ABI.md and it helps me a lot.
I just tried to parse the `.dll` file my self which is compiled (and signed) by Windows Intel SGX SDK.
The `sgxmeta` section is same with the structure that you explained in your document.
However, it seems that the `.tls` section just contains zeros .. :(

If you have any knowledge about where the TCS information is contained in the `.dll` file, could you please explain it to me?

Thanks a lot!

**Comment by jethrogb** [comment]
The .tls section is filled by the loader before running the enclave.

**Comment by jaebaek** [comment]
Got it. I just checked it.
Thanks!
