### ISSUE TITLE
enclave_example fails to compile

### ISSUE THREAD

**Issue by runjet** [jethrogb/sgx-utils#3]
When I try to compile the example it fails. Tried to install different versions of Rust with no luck.

`$ cargo build-enclave -H 0x10000 -S 0x10000
   Compiling enclave v0.1.0
   Compiling sgxs v0.4.0
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64:1: 64:71 error: the trait bound '*mut u8: core::marker::Send' is not satisfied [E0277]
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64 pub static USER_HEAP: Mutex<Option<Heap<'static>>> = Mutex::new(None);
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64:1: 64:71 help: run 'rustc --explain E0277' to see a detailed explanation
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64:1: 64:71 note: '*mut u8' cannot be sent between threads safely
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64:1: 64:71 note: required because it appears within the type 'alloc_buddy_simple::Heap<'static>'
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64:1: 64:71 note: required because it appears within the type 'core::option::Option<alloc_buddy_simple::Heap<'static>>'
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64:1: 64:71 note: required because of the requirements on the impl of 'core::marker::Sync' for 'spin::Mutex<core::option::Option<alloc_buddy_simple::Heap<'static>>>'
/home/runjet/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-0.1.0/src/alloc.rs:64:1: 64:71 note: shared static variables must have a type that implements 'Sync'
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile 'enclave'.

To learn more, run the command again with --verbose.
Error: CargoBuildExec(Status(ExitStatus(ExitStatus(25856))))
error: `

**Comment by jethrogb** [comment]
Sorry, this is https://github.com/mvdnes/spin-rs/issues/27. I'll hopefully release a fix this week.

**Comment by jethrogb** [comment]
Fixed in 0.1.2.
