### ISSUE TITLE
cargo build-enclave core_io issue

### ISSUE THREAD

**Issue by hsibyani** [jethrogb/sgx-utils#7]
Hello,

`cargo build-enclave -H 0x1000 -S 0x1000
`
gives

```
compiling core_io v0.1.20161028
error: failed to run custom build command for `core_io v0.1.20161028`
process didn't exit successfully: `/root/hassan/trusted/target/debug/build/core_io-e6c2a034de9ce8b9/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unknown compiler version, upgrade core_io?', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.

ERROR: There was an error executing `cargo rustc': Process exited with exit code: 101

```
Any ideas how to fix this?

Thank you.

**Comment by jethrogb** [comment]
You need to use a compiler old enough for the [core_io version](https://crates.io/crates/core_io) you're using

**Comment by hsibyani** [comment]
Thanks for the fast response. I think I have the latest nightly compiler (1.17), should I install an older version (before the latest core_io release)  instead?

**Comment by Pratyush** [comment]
To use `libenclave` and other SGX libraries you need a version of the compiler that works with the latest `core_io` release. @jethrogb just released a new version that works with the latest nightly. You should however pin the compiler version that you use by running `rustup override set nightly-$date` in your directory's project.
